### ISSUE TITLE
Power generators show incorrect storage of power in holograms and in the lore.

### ISSUE THREAD

**Issue by Boomer-1** [FN-FAL113/FN-FAL-s-Amplifications#55] opened 2022-03-12 15:49 UTC
Hey Fal, the R5 power generator shows a buffer of 5 million in the lore, but the R6 shows 600,000. 1-4 show 100-400,000 but 5 is multiplied by 10. in game it also shows 5 million in the hologram instead of 500,000.
the R12 power generator shows a lore of 2 million, but only displays 435525.

mc 1.18.1
sf version 1005
amplifications version 52

**Comment by FN-FAL113** [comment] 2022-03-13 01:38
Fixed in the next build, bad typo removed another 0 from the integer value

**Comment by FN-FAL113** [comment] 2022-03-13 01:45
![2022-03-13_09 43 00](https://user-images.githubusercontent.com/88238718/158041235-2d60c718-a1ae-460b-afd4-1c45d00eaa6e.png)
Can't seem to reproduce the issue for R12, have you tried deleting the yml file for power generators or checked the values inside for the r12 one?

**Comment by Boomer-1** [comment] 2022-03-13 03:43
before i did the last update video i had it placed for about 15 minutes and it never left the 435525 value. I've been trying for the last 5 minutes to see if it would stop but so far it is going to 2 million. not sure what is different now as I have never touched the config. I did have something new come up, not that it's a big deal. After placing one power generator and it fills the buffer, if you place a second power generator the buffer from the first one transfers to the second generator placed.

**Comment by FN-FAL113** [comment] 2022-03-13 03:55
https://user-images.githubusercontent.com/88238718/158044391-7c5ea1fe-4af8-44ca-92cf-71321dca5c45.mp4

Tried it, the energy from the first generator is still moving properly in my end. Buffers being transferred looks normal since the other one compensates it.

**Comment by Boomer-1** [comment] 2022-03-13 04:00
yeah, there's no loss of power so it's not really an issue, but you may get further comments on it.

**Comment by FN-FAL113** [comment] 2022-03-13 04:04
I'll leave this ticket open for a week, so others can comment.

**Comment by FN-FAL113** [comment] 2022-03-13 04:08
Next build requires deleting the yml for power generators to reflect the new capacity :)

**Closed** 2022-03-15 04:26 UTC
